# Generated by Django 4.1.1 on 2022-10-03 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
