# Generated by Django 4.1.1 on 2022-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passgen',
            name='site_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
