# Generated by Django 4.1.1 on 2022-10-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0002_alter_passgen_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passgen',
            old_name='time',
            new_name='created',
        ),
    ]
