# Generated by Django 4.1.1 on 2022-10-18 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_generator', '0003_rename_time_passgen_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passgen',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='passgen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passgen',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
